name: Build Branch
on:
    pull_request:

jobs:
    build:
        uses: flexbase-eng/.github/.github/workflows/typescript.build.yml@main
        with:
            use_packr: false
            package_folder: dist
