name: Deploy Package
on:
    push:
        branches: main

jobs:
    build:
        uses: flexbase-eng/.github/.github/workflows/typescript.build.yml@main
        with:
            use_packr: false

    dist:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Retrieve build artifacts
              uses: actions/download-artifact@v3
              with:
                  name: dist
            - name: Commit and push dist to main
              uses: stefanzweifel/git-auto-commit-action@v4.14.1
              with:
                  commit_message: 'Update dist version'
                  file_pattern: 'dist/index.js'
