name: Publish action
on:
    push:
        branches: main

jobs:
    build:
        uses: flexbase-eng/.github/.github/workflows/typescript.build.yml@main
        with:
            use_packr: false
            package_folder: output

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Retrieve build artifacts
              uses: actions/download-artifact@v3
              with:
                  name: dist

            - name: Commit and push binary to main
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'Update binary'
                  file_pattern: 'bin/index.js'
